### ISSUE TITLE
error when update from 2.6.1 to 3.0.0

### ISSUE THREAD

**Issue by bung87** [status-im/nim-chronos#174]
https://github.com/bung87/scorper/runs/2255382172
`
/Users/bung/.nimble/pkgs/chronos-3.0.0/chronos/asyncmacro2.nim(67, 17) Error: type mismatch: got <proc (udata`gensym105: pointer){.closure, locks: <unknown>.}> but expected 'proc (udata`gensym105: pointer){.closure, gcsafe.}'
`
Nim Compiler Version 1.4.4 [MacOSX: amd64]  

have no idea wh

**Comment by arnetheduck** [comment]
I've pushed a fix that fixes the immediate error - instead, there's now a warning printed - this is likely because https://github.com/bung87/scorper/blob/8bc79606e59d477ba0530009d210e6be9bb9f358/src/scorper/http/streamserver.nim#L170 or some other call in there cannot be determined to be `gcsafe` - happens with `importc` stuff sometimes, as well as forward declarations and callbacks.

With this fix in place, you'll get another error here: https://github.com/bung87/scorper/blob/8bc79606e59d477ba0530009d210e6be9bb9f358/src/scorper/http/futurestream.nim#L51 - you'll need to explicitly make sure `cb` doesn't raise, with https://github.com/bung87/scorper/blob/8bc79606e59d477ba0530009d210e6be9bb9f358/src/scorper/http/futurestream.nim#L10 adding `raises: []` per https://forum.nim-lang.org/t/7686

**Comment by bung87** [comment]
Thanks! I should read that thread earlier, let me try to fix.
