### ISSUE TITLE
async transformation doesn't handle implicit return

### ISSUE THREAD

**Issue by arnetheduck** [status-im/nim-chronos#28]
```nim
proc works(): Future[int] {.async.} =
  return 53

proc works2(): Future[int] {.async.} =
  result = 53

proc broken(): Future[int] {.async.} =
  53 # Error: expression '53' is of type 'int literal(53)' and has to be discarded
```
1357045cfa67dc9ca8299b36abab627a1de25511

**Comment by cheatfate** [comment]
This is very old known issue.

Because `async` macro is working with `untyped` arguments its impossible to fix it properly.

For example, if we are going to replace all unattended values with `result = <unattended value>` we can go to this problem:

```nim
proc empty() {.async.} =
  discard

proc notBrokenAnymore(): Future[int] {.async.} =
  await works()

proc notBrokenAnymore(): Future[int] {.async.} =
  53

proc nowBecomeBroken(): Future[int] {.async.} =
  await empty()
```

Because i can't check type of `empty()` i can't make transformation properly.

**Comment by arnetheduck** [comment]
Fixed in https://github.com/status-im/nim-chronos/pull/401
