### ISSUE TITLE
Compatibility to devel / Nim 2 + ORC

### ISSUE THREAD

**Issue by TechThupport** [status-im/nim-chronos#325]
Not really an issue but more of a clarification if chronos will be ported to be compatible with Nim devel branch or Nim 2. According to Araq the release should be happening soon or within 2022.

**Comment by Menduist** [comment]
The CI is ran with multiple Nim versions, including devel: https://github.com/status-im/nim-chronos/blob/master/.github/workflows/ci.yml#L25
It's impossible to guarantee devel compatibility at all time since they may break anything at anytime, but we try our best to be compatible with devel. I also think that chronos is part of the important_packages of the Nim CI

**Comment by TechThupport** [comment]
I'm mainly getting the below error when trying to compile with `--mm:orc` 

Not sure if this is only an issue for me or what. Chronos 3.0.11 installed:

```text
chronos/asyncmacro2.nim(126, 31) Error: 'handleRequest' is not GC-safe as it calls 'selectExt'
```
