### ISSUE TITLE
Async procedures and Defects.

### ISSUE THREAD

**Issue by cheatfate** [status-im/nim-chronos#81]
Currently `{.async.}` transformation catches all possible exceptions inside transformed procedures and stores it inside procedure's result Future[T] object.

As you can see here it catches all the exceptions:
https://github.com/status-im/nim-chronos/blob/master/chronos/asyncmacro2.nim#L55

Question is do we need to continue catching all possible exceptions or we should catch only `CatchableError` level?

This is one word fix.

CC: @arnetheduck @zah @mratsim @sinkingsugar @dryajov @kdeme

**Comment by cheatfate** [comment]
```nim
import chronos

proc badcode(): Future[void] {.async.} =
  await sleepAsync(0)
  echo "We should abort?"
  if true:
    raise newException(Defect, "Defect")
  echo "Unreached"

proc run() {.async.} =
  var swallowing: seq[Future[void]]
  for i in 0..9: swallowing.add(badcode())
  while true:
    await sleepAsync(100)
waitFor run()
```
This example demonstrate how `Defect` exception could be swallowed by not reading result of call.

**Comment by zah** [comment]
I have some specific related proposals that have been on my to-do list to share with you.

1) All user-implementable callbacks should have raises list `{.raises: [Defect].}`. This will force the user to handle all recoverable errors in the callbacks. Otherwise, the error is going to reach the even loop of Chronos and it will have to terminate the process.

2) Some API such as `allFutures` should propagate `Defects`. In other words, if even a single `Defect` happens in some of the operations, `allFutures` should re-raise it. I think it's acceptable that if multiple defects are raised, some information is lost. We can re-raise an arbitrary one of them.

**Comment by cheatfate** [comment]
@zah sorry but your proposal should have its own issue and discussion, because currently its offtopic.

**Comment by kdeme** [comment]
Well, point 2 is not fully offtopic as the choice made here will cause changes or removal for API calls such as `allFutures`.

I tend to agree that it would be nice if `Defects` are propagated to the call site. (and hence `allFutures` should be changed or even removed?).
However, it is not clear to me how we can then enforce the current example of not being possible.

**Comment by zah** [comment]
Yes, I think point 2 is related. When it comes to your example, we should consider any code that is effectively discarding a future as a programming error (discarding here means not subjecting to `traceAsyncErrors` or a similar API). 

`traceAsyncErrors` has a special code that terminates the program for any non-recoverable error:
https://github.com/status-im/nim-eth/blob/master/eth/async_utils.nim#L4-L14

**Comment by mratsim** [comment]
Side-note: One thing that isn't discussed and might influence the API is the expected logging.
Will it be done by the callee, the caller? How good are the traces with both Nim native backend and libbacktrace when they are callee-saved vs caller-saved.

Otherwise I think we should do the same as in C#. AFAIK they carefully implemented and evolved their API (even took inspiration from functional programming's monads) and currently they do propagate exceptions. This means less surprise for contributors who used C# (and probably Python and JS as well as it inspired those) and less documentation to explain the difference between Nim async and an established async framework.

Regarding the example apparently this is also an issue in C# and something that people have to learn.
> -   It's perfectly fine to have an async void method (such as an event handler) so long as you look after exceptions within that method
> -   Simply changing the signature doesn't prevent unhandled exceptions

https://blogs.msdn.microsoft.com/ptorr/2014/12/10/async-exceptions-in-c/

**Comment by dryajov** [comment]
I tend to agree with @zah on this one. There isn't anything better atm than `raises` and callbacks not handing their exceptions have been a long standing problem, so seems like the right path to take. This fixes all our issues relatively reliably, but it will of course be a breaking change and will lead to some reworking in the consumers.

**Comment by dryajov** [comment]
> Some APIs such as allFutures should propagate Defects. In other words, if even a single Defect happens in some of the operations, allFutures should re-raise it. I think it's acceptable that if multiple defects are raised, some information is lost. We can re-raise an arbitrary one of them

Yeah, except that I would simply re-raise on first raise in `allFutures`, that way you don't raise on every future, but at the call site of  `allFutures`.

**Comment by arnetheduck** [comment]
This is a fundamental issue with dividing the world into `Defect` and `CatchableException` and then arguing that sometimes you should use exception unwinding and be able to catch `Defect`:s - it's not logically sound and you will have to compromise somewhere - this is an example of such a compromise. 

Thus, this question doesn't have a logically sound answer: both approaches have unresolveable issues, so it's a bit random which one is chosen .

I'd probably not catch defects:
* easier to debug when the `Defect` happens immediately and not after the event handler loop potentially has processed other events 
* doesn't require someone remembers to process the future to detect the defect - ie if the future is not checked, the defect is lost - by not catching it here, there's less risk of it going undetected changing `allFutures` to propagate `Defect` doesn't help here as it's just one of many examples.

**Comment by zah** [comment]
> This is a fundamental issue with dividing the world into Defect and CatchableException

As it stands, this proposal is more strongly dividing the two categories. The spec will become "Defects unwind the stack and allow destructors to run, but only to the nearest Future boundary". This makes them a more special form of exceptions. It doesn't get you any closer to a world where there is no distinction.

I agree that terminating early reduce the potential for misuse, but it also eliminates two features:

* The ability to rely on destructors to perform a graceful shut down
* The ability to handle Defects from components that are not considered mission critical. Chronos is a general purpose library after all, it shouldn't have too strong opinions on these matters.

**Comment by dryajov** [comment]
>  Chronos is a general purpose library after all, it shouldn't have too strong opinions on these matters.
 
IMO, this is important and `Futures` and the networking related code should be separated.

 > I agree that terminating early reduce the potential for misuse, but it also eliminates two features:
>  
> The ability to rely on destructors to perform a graceful shut down
The ability to handle Defects from components that are not considered mission critical. Chronos is a general purpose library after all, it shouldn't have too strong opinions on these matters.

So far, all the discussions I've had, have departed from early termination. I think this is the right way to go, we shouldn't terminate early because we introduce a new twist where cancelation should be handled as a separate case. In other words, `allFutures` should not bail out on first fail, it should allow all `Futures` to finish correctly and then allow to handle for errors.

**Comment by dryajov** [comment]
I should clarify, that the event loop code + futures should be separate from the networking code, but that is ofcourse a different issues altogether.

**Comment by sinkingsugar** [comment]
> The ability to handle Defects from components that are not considered mission critical. Chronos is a general purpose library after all, it shouldn't have too strong opinions on these matters.

Turn that specific `Defect` you want to handle into a `CatchableError` and done.

As it stands now the definition of the word `Catchable` is not respected cos we make `Defect` also catch-able here so the distinction is pointless and confusing at the moment while it should be a strong distinction, I wish nim made it clear by calling `abort()` panic rather then reusing `Exception` on `Defect` so we would not have this conversation at all 😄 

https://en.cppreference.com/w/cpp/error/assert
> If NDEBUG is not defined, then assert checks if its argument (which must have scalar type) compares equal to zero. If it does, assert outputs implementation-specific diagnostic information on the standard error output and calls std::abort. The diagnostic information is required to include the text of expression, as well as the values of the standard macros __FILE__, __LINE__, and the standard variable __func__ (since C++11).

This is my education on asserts... Why nim has to have its own twisted take on every simple system language concept is out of my understanding.

Rust take:
Similar to C++ but they allow to catch panic in a very **EXPLICIT** way:
https://doc.rust-lang.org/std/panic/fn.catch_unwind.html

**Comment by dryajov** [comment]
@sinkingsugar I have the same stance, this should abort - ie, `Defects` should not be handled and definitely shouldn't be ever swallowed. Our api's should never throw a `Defect` and things like `allFutures` should make it impossible for the consumer to ever miss a non fatal (which should just abort) exception, such as `CatchableError`.

**Comment by cheatfate** [comment]
Because this issue is full of offtopic messages and full of unrelated dispute, i'm going to close this issue. And `Exception` will be changed to `CatchableError`.

**Comment by cheatfate** [comment]
Behavior was changed in 56fbdff096c3fa349001468b8a9311bbe1cac0f4

**Comment by arnetheduck** [comment]
> The ability to handle Defects from components that are not considered mission critical. 

"strictly uncatchable"

https://github.com/nim-lang/Nim/blob/31332bca450c8b681802802e06342353abf9dd20/lib/system/exceptions.nim#L44

as @sinkingsugar points out, a critical problem here is that the mechanism for handling catchables and defects should not be the same, but in nim it is (`catch` in both cases) - this further makes it difficult to keep the two apart and reason about sound behaviour because finding the code that uses it is hard.

> As it stands, this proposal is more strongly dividing the two categories. 

I agree with this and I wish it were not so - but it is. we can't have it both ways - the problem is not isolated to this async transformation but creates follow-up problems down the line if we treat the definitions ambiuously. 

In this case, keeping processing the async queue after a defect has happened might equally be the lesser evil - because of the proliferation of `ref` and the lack of deterministic destruction in the foreseeable future, no unwinding will happen anyway.

Because we are in undefined behaviour territory and upstream issues on `Defect`'s remain, it's useless to try to write code for a future that may not come to pass - these decisions will be off anyway, so we can go with whatever is most convenient with the behaviour that exists _now_, and change it when/if upstream changes. Specifically, there remain open questions about which defects are raised when, which are enforced by raises, sysFatal vs raise, abort vs unwind and more - they have been open for months/years with no hope in sight for them to be resolved swiftly.

**Comment by zah** [comment]
> "strictly uncatchable"

I've talked many times with @Araq regarding errors vs defects and he is actually in the other camp. He believes that it's quite reasonable for some type of software to decide that defects can be ignored in certain situations. His favourite example is a web server where you may want to ignore defects during the processing of a single web request (you reply with 505 and continue). I also think that handling defects should require extra steps, but it should be possible. I've given as example an email client that may try to use a "zip" library to decompress an attachment. It may decide to report any defects in the zip library as a generic error displayed in a GUI message box.

>  lack of deterministic destruction in the foreseeable future

According to my latest tests, the destructors already work well enough in Nim 1.0.6 (also, without the need to compile with --gc:arc)! 

Since @dryajov and @sinkingsugar are new to these discussions, I'll mention why I believe it's preferable for the defects to lead to stack unwinding (with the associated execution of destructors) instead of simply aborting the program. I usually describe this as supporting [graceful shutdown](https://en.wikipedia.org/wiki/Graceful_exit):

When the program exits, the OS will take care of releasing many of the allocated resources (such as network connections and open ports, locked files, etc), but some of these may be distributed resources (in-flight database transactions, distributed locks, quorum memberships, etc). If they are not released during a graceful shutdown, they will have to expire with a timeout, but such timeouts are often quite conservative (measured in minutes) and this can make the recovery of a crash significantly more costly. Sometimes even the local resources may require a proper clean-up (e.g. we have probably all used a text editor that will leave junk files in your working copy when it crashes).

>  change it when/if upstream changes

As a temporary measure that helps with investigation, I think the merged change above may prove to be useful, but I hope this is not our long-term policy due to the extra requirements presented above.
